### ISSUE TITLE
Actions reusable or not

### ISSUE THREAD

**Issue by andrewgazelka** [ezAuton/ezAuton#102]
# Should Actions be able to be Reused?

## What are actions

Look [here](https://github.com/ezAuton/ezAuton)

## What do you mean reusable 
Able to be run more than one time per instantiation 

## TL;DR

**If actions are reusable** we will need to trust that implementations of `run(ActionRunInfo)` are pure, thus avoiding issues with states. 

**If they are NOT reusable**, this will add more (perhaps unnecessary) restrictions to the user, but will add the benefit of less confusing errors for naïve programmers. To enforce this, we could keep track of actions and throw an `ActionReusedException` if someone tries to run an action twice.

**Question:**
Should we allow extra freedom with the loss of having a high chance of a naïve programmer having code with confusing errors?

## Note
My notes here are not consise and I am building upon what I have written generally higher up in the note. I will probably edit this several times and the end will have a much clearer and cleaner solution than the beginning.

## Explanation
Currently the action are defined as:
![image](https://user-images.githubusercontent.com/7644264/56225233-91ac4f00-6036-11e9-8ab0-d8501721a893.png)

There is expected to be a new instantiation for every `run(ActionRunInfo)` call. This allows us to have less state conflicts. If we reuse of actions, one process changing the state of the action being used by another process which is not expecting the state to be changed can result in issues. 

However, creating a new instance does have downsides:
- WPILib Commands can be reused, so this might be unwanted variance between the standard library... **HOWEVER, as we will see in case examples, the structure of actions would actually be quite drastically different.**
- Commands cannot be reused

If actions must be reused, their properties set by their constructor should be read-only and not modified—even by `run(ActionRunInfo)`. If this is not the case, it can lead to several problems. For example, two concurrent actions which write values to property `a` will most likely expect `a` to only be relevant to that action. However, as both processes are modifying it as they please the runtime of each action will bleed into each other and cause unexpected issues ([side-effects](https://en.wikipedia.org/wiki/Side_effect_(computer_science))), such as would be the case with a [naïve implementation of an action cancellation mechanism](#canceling-actions). Even if side effects somehow did not cause problems, we could still get a `ConcurrentModificationExceptions` for modifying values concurrently. Heck, the whole [value of a 64 bit PRIMITIVE value might be completely wrong](https://stackoverflow.com/a/9278798/4889030). Therefore, `run(ActionRunInfo)` would need to always be a [pure function](https://en.wikipedia.org/wiki/Pure_function) and we would need to trust that people would not implement it wrong. 

### ActionGroups
Another example of where action reuse might be nice: `ActionGroup`s. Reusing them would allow us to make a group ONCE and then easily use it in multiple places. However, note how we mentioned all properties msut be read only. This means we would not be able to have `addParallel(Action)`, `addSequential(Action)`, ... methods as if they are called when another process is already running, it will cause havoc. Instead, we would need to pass in action info into the constructor and an immutable list  of actions would be stored. Hence, we would have an `ActionGroupBuilder` for having `addSequential(Action)` and other methods. Additionally, all tracking of how many actions are left to schedule would be implemented in the  pure method, not a field in the class.

### Canceling actions
We mentioned we wanted all fields to read-only. However, what if we want to have implementation for cancelling an action? We couldn't have a `Action#end()` as it would change the state of a field (perhaps `isEnded`) which would propagate (and end) other instances of the action being used. Instead, we would need to remove all methods from `Action` except `run(ActionRunInfo)`. Thus `Action` would act as a lambda.

#### Then how would we cancel actions?
The method `run(ActionRunInfo)` would need to return a handler which would allow us to manage an action. This would be quite similar to a Java `Future<O>` except for the `Action` framework. It would include:
- `end()` 
- `interrupted()` 
- `onFinish(Runnable)` 
- `getFinished()`

However, how would we even do this? `run(ActionRunInfo)` blocks and things can only be returned at the end of a function. Thus, the state could only be returned (and accessed) after the action is done finishing which does not make any sense if we need to cancel an action mid-state.

So how else would we be able to do this?

### A Naïve Scheduler 
We would need to make the `run` method `run(ActionRunInfo, ActionGoal)`, where `ActionGoal` would include mutable arguments which define whether the action should be ended and can be checked in the implementation of `run()`. This might seem confusing to pass in, but note that `Action`s are not run directly—instead, they are run through a scheduler framework. The scheduler framework currently returns a `Future` which can be used for cancelling the action—but very dramatically through thread suspension. Instead we could have a structure like so 

![image](https://user-images.githubusercontent.com/7644264/56236788-fde77c80-604f-11e9-8dd7-5db5d35dd19d.png)

#### Polling is bad
To see if we have been interrupted, we would need to constantly check the status of `ActionGoal#cancelled`. This would create very sloppy  code like such

```kotlin

void onCancel() = TODO()

void run(info: ActionRunInfo, goal: ActionGoal){
    // do something A
    clock.sleep(1_000)
    if(goal.cancelled){
        onCancel()
        return
    }

    // do something B
    clock.sleep(1_000)
    if(goal.cancelled){
        onCancel()
        return
    }

    // ...
}
```
this is really ugly and the process won't even stop until AFTER the sleep is finished!!!

Let's look at how Java does this
#### Callbacks are better
It might be better to look at how Java handles interrupting a sleeping `Thread`. Java uses exceptions as events (callbacks). We could argue that this is bad because 

> [Exceptions should only be used in exceptional cases](https://softwareengineering.stackexchange.com/a/184714/306473)

but I would argue this is an exceptional case... regardless, the main Java library does it anyways and [Java LOVES exceptions](https://softwareengineering.stackexchange.com/a/184696/306473).

```kotlin

void onCancel() = TODO()

void run(info: ActionRunInfo){ // Note we can remove goal

    // do something A
    try{
        clock.sleep(1_000)
    }catch(InterruptedException e){
        onCancel()
        return
    }

    // do something B
    try{
        clock.sleep(1_000)
    }catch(InterruptedException e){
        onCancel()
        return
    }

    // ...
}
```
In this scenario, `ActionRunInfo` would just need a `Future`, not an `ActionGoal`, since Java native `Future`s link to where they are scheduled and offer a `cancel(boolean)` method which will interrupt the process.

![image](https://user-images.githubusercontent.com/7644264/56238393-0a6dd400-6054-11e9-8d4a-3594bf055a10.png)

### Where is Action now?

After our design changes since the beginning, we have the following structure.

![image](https://user-images.githubusercontent.com/7644264/56239013-874d7d80-6055-11e9-8703-8737442a4b4f.png)

Also if you are wondering what `ActionRunInfo`, it is a data class which combines `Clock` (which is used for keeping track of time in potentially scheduled environments & sleeping) and also the `ActionScheduler` it was scheduled with (so it can schedule more sub-actions).

![image](https://user-images.githubusercontent.com/7644264/56239363-620d3f00-6056-11e9-8e86-12129d4410e6.png)

### Get more information about cancellations

This is a segue into another issue, but perhaps we want the `Action` to have more information than just that there _is_ an interrupt when one occurs. 

#### Types of useful information to know
- **Why**
  - Another `Action` wanted force access to a resource the current action is using
  - the robot was disabled
  - it is a with action of `ActionGroup` 
  - an `ActionGroup` containing it cancelled

#### How this can be processed
We can create subclasses of `InterruptException` for each of these so we can use `instanceof` to check which case we need to cover. We would also be able to bundle additional information in each subclass if needed.

#### Futile attempts to send subclasses
Welp, we are running into a problem again. We want a pure function, but we need to transfer new data to it and currently the flow of the `InterruptedException` is

```
Future#cancel() > ExecutorService > interrupt running process
```

We most likely don't want to make a custom `ExecutorService` and custom `Future` to be able to send custom `InterruptExceptions`. 

Also, we could add back some type of second parameter like `ActionGoal` but one which contains data about the type of error. This is quite jank though and I would prefer this to be avoided.

Finally the clock system (which is used for blocking) could be rewritten so that `sleep(Long)` can wrap the thrown `InterruptException`s, somehow correlate the reason to each action and create and throw a custom `InterruptException`. We do not want to change the signature from `sleep(Long)` to `sleep(Long, Action)`. It might seem like we have no other options, but this is actually useful. 

#### Solution to sending subclasses
Let us create `ActionFuture` interface which is a future but allows for throwing custom exceptions. We will have:
```kotlin
interface ActionFuture extends Future<Void> {
    fun cancelWithException(exception: InterruptedException)
}
```

We will implement it using delegates which is a [composition shortcut in Kotlin](https://proandroiddev.com/composition-over-inheritance-in-kotlin-way-fe341159bf1c). Additionally, we will link it to an `ActionClock` which is a wrapper for the `Clock` which has `sleep(...)` methods. Thus, the action clock will be able to change the exception if needed.
```kotlin

private class ActionClock(val clock: Clock) : Clock by clock {

    companion object {
        fun wrap(other: Clock): ActionClock {
            return ActionClock(other)
        }
    }

    private var toThrow: InterruptedException? = null

    // TODO: Needed to do this to properly encapsulate toThrow. Is this a good idea?
    class Future(private val actionClock: ActionClock, private val toWrap: java.util.concurrent.Future<Void>) : ActionFuture, java.util.concurrent.Future<Void> by toWrap {
        override fun cancelWithException(exception: InterruptedException) {
            actionClock.toThrow = exception
        }
    }

    // TODO: is this bad??? if clock: Clock decides  to use sleep, it could cause to be inconsistent
    override fun sleep(dt: Long, timeUnit: TimeUnit?) {
        val throwLocal = toThrow
        if (throwLocal == null) {
            clock.sleep(dt, timeUnit)
        } else {
            try {
                clock.sleep(dt, timeUnit)
            } catch (exception: InterruptedException) {
                throw throwLocal
            }
        }
    }
}
```

![image](https://user-images.githubusercontent.com/7644264/56250842-adcfe080-6076-11e9-94f7-63300221305a.png)

**Comment by andrewgazelka** [comment]
After a very long time thinking about this, I have decided—along with help of solomon from 2898—that actions most likely should not be reused. This is due, in part, to the following reasons:
- we would need to rewrite a large portion of the `Action` framework
- there would be many breaking API changes for those using `ezAuton`
- there is not enough of a reason to convert to reusable actions as if programmed right, their behavior will be nearly identical to non reusable actions.
- getting data from `Action`s (i.e., when recording) is very tough if they are reusable due to all variables being read-only. 

If anyone else has other, differing opinions, I will re-open this issue.

**Comment by ritikmishra** [comment]
ok this is not pertinent to the issue but how did you make these diagrams?

**Comment by andrewgazelka** [comment]
> ok this is not pertinent to the issue but how did you make these diagrams?

[IntelliJ Class Diagrams](https://www.jetbrains.com/help/idea/class-diagram.html)
