### ISSUE TITLE
Should ActionScheduler be able to accept vararg actions?

### ISSUE THREAD

**Issue by andrewgazelka** [ezAuton/ezAuton#107]
Will help being consise. However, this might be ambiguous to someone new to ezAuton on whether it is parallel or sequential. Perhaps people should just use ActionGroups.

**Comment by ritikmishra** [comment]
They should just use ActionGroup.of(some sequential actions)

**Comment by andrewgazelka** [comment]
actually `ActionGroup.ofSequential()`or `ActionGroup.ofSequential()`... action groups require explicitly stating type to run, which is good imo. Closing.
