### ISSUE TITLE
Fix TankRobotTransLocDriveable constructor

### ISSUE THREAD

**Issue by ritikmishra** [ezAuton/ezAuton#125]
### Problem
The problem is that `TankRobotTransLocDriveable#driveTowardTransLoc(double speed, ImmutableVector loc)` wants `speed` to be in linear units (i.e `ft/s`).

This is problematic because the constructor for `TankRobotTransLocDriveable` takes in two `VelocityMotors.` A `VelocityMotor` should only know about its RPM, since linear `ft/s` does not make sense for motors that may need to run at a particular velocity (e.g flywheel shooter), but aren't involved in linear motion.

### Proposed Solution

Create an interface `LinearVelocityMotor implements VelocityMotor`.

**Comment by andrewgazelka** [comment]
Use `EncoderWheel` instead? Having a `LVM extend VM` is like having `Sphere extend Circle`. Properties (i.e., area <-> volume) are different and they shouldn't be in a hierarchy together. The same goes for `rpm <-> ft/s`. 

Think if `LVM extend VM` was true... then there would be no static type checking for any argument which took in a `VM`. It would have no idea if it was in rpm or fps.
