### ISSUE TITLE
The medium article is missing

### ISSUE THREAD

**Issue by Sargeanthost** [ezAuton/ezAuton#134]
[Medium — How to use ezAuton to write cleaner code for FRC](https://medium.com/@andrew.gazelka/how-to-use-ezauton-to-write-cleaner-code-for-frc-ea18d0243936) returns a 410.

**Comment by andrewgazelka** [comment]
Thanks for reminding me of this! I wrote a simple tutorial in the README. I will  be working on expanding it.
