### ISSUE TITLE
Add maven repo

### ISSUE THREAD

**Issue by andrewgazelka** [ezAuton/ezAuton#15]
We should have a maven repo for ezAuton. Should it be hosted on GitHub or some other source? @ritikmishra

**Comment by andrewda** [comment]
Not sure if you've considered it yet, but https://jitpack.io is awesome! Looks like this repo is already building perfectly, so it can probably be implemented as easy as:

```
repositories {
    maven { url "https://jitpack.io" }
}

dependencies {
    compile "com.github.ezAuton:ezAuton:f1df629c8d"
}
```

Build log: https://jitpack.io/com/github/ezAuton/ezAuton/master-f1df629c8d-1/build.log

**Comment by andrewgazelka** [comment]
Looks sweet. We will definitely try to get users to use this option. :)
