### ISSUE TITLE
Multiple sub-projects

### ISSUE THREAD

**Issue by ritikmishra** [ezAuton/ezAuton#27]
This should allow for greater separation of the core API from WPILib-specific helper methods and logging utilities. 

Ideally, we would have subprojects for
- The core API
- WPILib-specific utilities
- FTC-specific utilities
- The GUI for viewing PP logs
- A Path-creation GUI

**Comment by andrewgazelka** [comment]
Great idea. I'll start by separating the core API and WPILib. I'll save the rest for you since you are far more familiar with those than I.

**Comment by ritikmishra** [comment]
Thanks!

**Comment by andrewgazelka** [comment]
Probably not the best name, but I started this in https://github.com/ezAuton/ezAuton/tree/feature-seperate xD

**Comment by ritikmishra** [comment]
Thanks a lot!!!
