### ISSUE TITLE
Method overriding issue

### ISSUE THREAD

**Issue by andrewgazelka** [ezAuton/ezAuton#46]
PeriodicAction overrides `IAction#run()`with its loop logic. However, this is kinda bad because some dumbo might not know that he can't override `Periodic#run()`. Is there a good solution to this?

**Comment by ritikmishra** [comment]
Make it final and create an interface akin to command that periodic action wants? Don't have other ideas right now

**Comment by andrewgazelka** [comment]
by 
> final
you mean `PeriodicAction`?

**Comment by ritikmishra** [comment]
yes

**Comment by andrewgazelka** [comment]
hmm seems janky, but I honestly can't think of any better way to do this.

**Comment by ritikmishra** [comment]
wait can you make methods final?

--
Ritik Mishra

**Comment by andrewgazelka** [comment]
you can... we should do that for sure.
