### ISSUE TITLE
latest version ezAuton not on jitpack?

### ISSUE THREAD

**Issue by andrewgazelka** [ezAuton/ezAuton#59]
RobotStateRecorder is red in WPILibExample

**Comment by andrewda** [comment]
Seems like the latest commit passed: https://jitpack.io/com/github/ezAuton/ezAuton/390bd65f71/build.log

**Comment by andrewgazelka** [comment]
Ah... it was probably because the repo wasn't compiling before (because of GradleRIO updates). Will close.
