### ISSUE TITLE
Change package name org ==> com?

### ISSUE THREAD

**Issue by andrewgazelka** [ezAuton/ezAuton#61]
Should we change the package name from 
`org.github.ezauton.ezauton`
to
`com.github.ezauton.ezauton`?

I only used `org` because a project I work with often (PaperSpigot) has `org.github.{projectName}` instead of `com.github.{projectName}` and I have no idea why. org for organization, maybe?

**Comment by ritikmishra** [comment]
I don't want to for no other reason than it will be kind of a pain and it doesn't really matter (right?)

**Comment by andrewgazelka** [comment]
@ritikmishra well, it is a simple refactor that would take 30 seconds to do. If we want to do it, though, we better do it sooner than later before a bunch of people are importing our library (we don't want to break things!).

**Comment by andrewgazelka** [comment]
but yes, I don't think it really matters.

**Comment by pbriggs28** [comment]
Yea that sounds perfect.
`com.github.ezauton.core`
`com.github.ezauton.visualizer`
`com.github.ezauton.recorder`
`com.github.ezauton.wpilib`
