### ISSUE TITLE
Move partly to Kotlin?

### ISSUE THREAD

**Issue by andrewgazelka** [ezAuton/ezAuton#62]
I really love Kotlin, but I know some people who contribute to this project don't use it. Now that I have learned a bit of it, I feel so sluggish writing anything in Java... 

Kotlin is amazing because it works fine having parts of the project in Java and parts in Kotlin. Are we alright doing this? Here are some advantages of Kotlin:

- 100% interoperable Kotlin <=> Java
- optional parameters (and defaults)
- wrapped reference objects (no need for AtomicObjects in lambas for reference)
- objects (Singleton shortcut)
- very well-defined immutable vs mutable collections 
- able to wrap last arg higher-order functions after a function.. i.e. `thread { println("Hello") }`
- functions not bound to classes
- no required semi-colons
- delegate methods / no need for annoying getter/setter methods (i.e., `val time get() = System.out.currentTime()`)
- `val` and `var`
- generators (and coroutines)
- `` fun `can name functions like this which is nice for junit testing()` = Assert.assertEquals(2,2) ``
- operator overloading
- extension functions for bad APIs (this might be nice if we want to add extension functions to the WPILib API)
- ...

**Comment by andrewgazelka** [comment]
since I am impatient, I will start in a new feature branch and delete it if people don't like it.

**Comment by andrewgazelka** [comment]
also, forgot to mention... nullability is a really key aspect of Kotlin. It is very hard to get a NPE in Kotlin, but you can still use null values you add `?` after the class type. It is infinitely better than the Java `Optional<V>` class.

**Comment by andrewgazelka** [comment]
and imo enforces better good practices as well (everything is by default `final`)

**Comment by ritikmishra** [comment]
ok so kotlin has all these great feature

How do you want to apply them and how will that prevent people who don't know kotlin from contributing to the project?

**Comment by andrewgazelka** [comment]
well, if you look at the current source code, we don't need a large percent of classes to be in Kotlin. I think a lot of people who are using special third-party libraries also have a large chance of using Kotlin. I don't think it really is going to change things up for the contributors a whole ton... especially since I am only using it for unit tests now, which people more add on to and not modify.

Probably sound completely illiterate, really tired lol

**Comment by andrewgazelka** [comment]
@ritikmishra are you alright with me merging this then?

**Comment by ritikmishra** [comment]
> I think a lot of people who are using special third-party libraries also have a large chance of using Kotlin

I very strongly disagree. This year, the default build system is Gradle, making it *significantly* easier to use a third party library without a lot of technical knowledge when compared to Ant.

**Comment by andrewgazelka** [comment]
![image](https://user-images.githubusercontent.com/7644264/50982409-c1413d80-14c2-11e9-8096-76d7dc1e9a59.png)

Proving my point :p

**Comment by andrewgazelka** [comment]
look, I'll definitely move from Kotlin back to Java if people start complaining, but until that point, I think the benefits outweigh the costs.

**Comment by ritikmishra** [comment]
fine.

**Comment by AlecDusheck** [comment]
+1. The learning curve isn't huge and Kotlin looks super cool.
