### ISSUE TITLE
Are Updateables even useful?

### ISSUE THREAD

**Issue by andrewgazelka** [ezAuton/ezAuton#63]
Should we even use `Updateable` interface? I think, to say the least, we are overusing it. For example, `BackgroundAction` and `TimedPeriodic` both have `Updateable...` params, but they do nothing with the values returned. Kinda dumb imo.

**Comment by andrewgazelka** [comment]
I believe the argument I had in my brain was most things in a `BackgroundAction` should be things which are updated periodically for a long time (since it never stops). Most of these things would be `Updateable`s, but not all. I might have thought that it would look ugly calling the `update()` method on `Updateable` objects, but this isn't really the case. If `BackgroundAction` takes in `Runnable`s, we can just use `updateableObj::update` and it serves as a runnable.

**Comment by ritikmishra** [comment]
(alternatively you can have `Updateable implements Runnable` with `default run() { update() }` if it's a common use case)

I don't recall ever seeing a situation where an Updateable returned false in our code, and I would imagine if it did have to return false it would throw an exception instead . . .

**Comment by andrewgazelka** [comment]
I mean, it could definitely be useful, but as of now it is being forced where it _isn't_ useful. I agree. I'm going to close.
