### ISSUE TITLE
codecov stopped working 5 months ago

### ISSUE THREAD

**Issue by andrewgazelka** [ezAuton/ezAuton#66]
No wonder code coverage has not been increasing. For some reason it stopped 5 months ago. The last commit tested was 5b749e350ae362d4d1adad4f7071fabdb3cf1d50 and the commit after that was 48e98778cbf7f2d6e6d16e8348dafb14a8859de7. Commits are [here](https://codecov.io/gh/ezAuton/ezAuton/commits). Any idea why it suddenly stopped working? 

Currently using travis, https://github.com/ezAuton/ezAuton/blob/master/.travis.yml

**Comment by ritikmishra** [comment]
perhaps the webhook for the repo broke or something?

**Comment by andrewgazelka** [comment]
Possibly, but 
![image](https://user-images.githubusercontent.com/7644264/51045839-31ff5d00-158a-11e9-96b2-709ad7585488.png)

**Comment by andrewgazelka** [comment]
also latest Travis-CI build:
![image](https://user-images.githubusercontent.com/7644264/51045875-43e10000-158a-11e9-99fb-a04496dc0b8a.png)

**Comment by ritikmishra** [comment]
try it manually?

**Comment by andrewgazelka** [comment]
![image](https://user-images.githubusercontent.com/7644264/51046061-bbaf2a80-158a-11e9-90de-6cca17e582d1.png)
think I found the issue. We don't have a webhook enabled...

**Comment by andrewgazelka** [comment]
oh nvm

**Comment by andrewgazelka** [comment]
Fixed for some reason in 4cb9edcaf03ebb9c34bcd6bd288e73ad082eafd5
