### ISSUE TITLE
java 11?

### ISSUE THREAD

**Issue by ritikmishra** [ezAuton/ezAuton#78]
currently the sourceCompatibility/targetCompatibility of the project is 1.8 and wpilib is on 11 now

**Comment by andrewda** [comment]
This is fine because Java 1.8 is fully forwards compatible with later JVMs, including the JVM 11. In fact, Kotlin only works when the source/target compatibility is set to 1.6 or 1.8 because I think Android runs on 1.8 still.

**Comment by ritikmishra** [comment]
ok sounds good
