### ISSUE TITLE
is it good that throughout API 0 rads is the forward direction of the robot?

### ISSUE THREAD

**Issue by andrewgazelka** [ezAuton/ezAuton#90]
I found this much easier for some reason. Right now 0 radians is facing forward for the robot (and increases CCW). Is this a bad idea (compared to pointing to the right side)?

**Comment by ritikmishra** [comment]
From a mathematical perspective people would not expect that the vector `<cos theta, sin theta>` does not point in the direction of the robot

From a practical perspective, it is simpler and more intuitive to calibrate the robot's gyro to 0 when starting rather than Math.PI / 2

**Comment by andrewgazelka** [comment]
@ritikmishra so what do you think is better? :p I think probably the practical perspective.

**Comment by ritikmishra** [comment]
me too
