### ISSUE TITLE
get rid of IAction#getFinished() and IAction#onFinish()

### ISSUE THREAD

**Issue by andrewgazelka** [ezAuton/ezAuton#91]
why? ... it is ambiguous whether `onFinish()` will be executed when interrupted or peacefully finished. The syntax is also slightly jank and might be confusing for people.

**Comment by ritikmishra** [comment]
Is it used by other actions?

**Comment by andrewgazelka** [comment]
> Is it used by other actions?

Action _Implementations_? No... it is currently used in unit tests and `ModernSimulatedClock`, but I am not sure it is needed there either. If we do keep it, we should definitely figure out _when_ it should be called.

**Comment by andrewgazelka** [comment]
I think this whole callback syntax is kinda bad. Additionally, imo an `Action` should not worry about managing things to run on finish. I think it is better to just use an `ActionGroup` as it is more explicit. In Kotlin, we could make this an _extension function_ 
```kotlin
fun Action.after(other: Action) = ActionGroup.ofSequential(this, other)
```
we could then chain these together (which would result in nested ActionGroups, but with error propagation this is probably ok).
