### ISSUE TITLE
testSpline() does not pass 100% of the time

### ISSUE THREAD

**Issue by andrewgazelka** [ezAuton/ezAuton#94]
in fact it passes a very small % of the time. Issue is the simulation (usually) throws a `TimeoutException`—even after 30 seconds.

**Comment by ritikmishra** [comment]
it's probably lookahead

**Comment by andrewgazelka** [comment]
> it's probably lookahead. for splines to perform you need to reduce it to below the lookahead that is used for linear paths.

we should probably run the recorder to see what is going on.

**Comment by andrewgazelka** [comment]
Update:
```
com.github.ezauton.core.purepursuit.PPSimulatorTest > testSpline() FAILED
    org.opentest4j.AssertionFailedError at PPSimulatorTest.java:141
```

[Source | TravisCI](https://travis-ci.org/ezAuton/ezAuton/builds/523730571)
